# Generated by Django 5.2.12 on 2026-03-16 19:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.CharField(db_index=True, default='default', max_length=64)),
                ('batch_no', models.CharField(blank=True, default='', max_length=64)),
                ('on_hand', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product')),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='inventory_on_hand_non_negative'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='inventory_reserved_non_negative'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='inventory_reserved_lte_on_hand')],
            },
        ),
    ]
